name: Run tests
on:
  push:
    branches: [master]
jobs:
  execute_tests:
    name: Install requirements and execute tests
    runs-on: ubuntu-22.04
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9, 3.10]
    steps:
      - name: Update
        run: sudo apt update
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install pip
        run: sudo apt install python3-pip
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Execute tests
        env:
          DJANGO_SETTINGS_MODULE: mysite.settings
        run: pytest
