name: Run tests
on:
  push:
    branches: [master]
jobs:
  execute_backend_tests:
    name: Install backend requirements and execute tests
    runs-on: ubuntu-22.04
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.9"]
    steps:
      - name: Update
        run: sudo apt update
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pip
        run: sudo apt install python3-pip
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Execute tests
        env:
          DJANGO_SETTINGS_MODULE: mysite.settings
        run: pytest
  execute_frontend_tests:
    name: Install frontend requirements and execute tests
    runs-on: ubuntu-22.04
    strategy:
      max-parallel: 4
      matrix:
        node-version: ["18"]
    defaults:
      run:
        working-directory: ./FRONTEND/polls_test_ui/
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node and Cache
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: FRONTEND/polls_test_ui/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Lint Check
        run: npm run lint
